"""Generate error-analysis artifacts from an evaluation CSV.

Expected CSV columns:
    latitude, longitude, pred_latitude, pred_longitude, haversine_m

Example:
    python scripts/analyze_errors.py --predictions outputs/predictions.csv --out-dir outputs/error_analysis
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from img2gps.constants import GRID_N, LAT_MAX, LAT_MIN, LON_MAX, LON_MIN  # noqa: E402
from img2gps.geo import gps_to_cell  # noqa: E402


def assign_cells(df: pd.DataFrame) -> pd.Series:
    return df.apply(lambda row: gps_to_cell(float(row["latitude"]), float(row["longitude"])), axis=1)


def save_error_histogram(df: pd.DataFrame, out_dir: Path) -> None:
    plt.figure(figsize=(8, 5))
    plt.hist(df["haversine_m"], bins=30)
    plt.xlabel("Haversine error (m)")
    plt.ylabel("Number of images")
    plt.title("img2GPS error distribution")
    plt.grid(alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_dir / "error_histogram.png", dpi=200)
    plt.close()


def save_grid_error_heatmap(df: pd.DataFrame, out_dir: Path) -> None:
    df = df.copy()
    df["cell_id"] = assign_cells(df)
    grid = np.full((GRID_N, GRID_N), np.nan)
    for cell_id, group in df.groupby("cell_id"):
        row = int(cell_id) // GRID_N
        col = int(cell_id) % GRID_N
        grid[row, col] = group["haversine_m"].mean()

    plt.figure(figsize=(7, 6))
    plt.imshow(grid, origin="lower")
    plt.colorbar(label="Mean Haversine error (m)")
    plt.xlabel("Grid column")
    plt.ylabel("Grid row")
    plt.title("Mean error by ground-truth grid cell")
    plt.tight_layout()
    plt.savefig(out_dir / "grid_error_heatmap.png", dpi=200)
    plt.close()


def save_summary(df: pd.DataFrame, out_dir: Path) -> None:
    summary = {
        "samples": int(len(df)),
        "mean_m": float(df["haversine_m"].mean()),
        "median_m": float(df["haversine_m"].median()),
        "p75_m": float(df["haversine_m"].quantile(0.75)),
        "p90_m": float(df["haversine_m"].quantile(0.90)),
        "max_m": float(df["haversine_m"].max()),
        "lat_range": [LAT_MIN, LAT_MAX],
        "lon_range": [LON_MIN, LON_MAX],
    }
    pd.Series(summary).to_json(out_dir / "summary.json", indent=2)

    worst = df.sort_values("haversine_m", ascending=False).head(20)
    worst.to_csv(out_dir / "worst_20_predictions.csv", index=False)


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze img2GPS prediction errors")
    parser.add_argument("--predictions", required=True, help="CSV generated by img2gps.evaluate")
    parser.add_argument("--out-dir", default="outputs/error_analysis")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(args.predictions)

    required = {"latitude", "longitude", "pred_latitude", "pred_longitude", "haversine_m"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    save_error_histogram(df, out_dir)
    save_grid_error_heatmap(df, out_dir)
    save_summary(df, out_dir)
    print(f"Saved error-analysis outputs to {out_dir}")


if __name__ == "__main__":
    main()
